[build-system]
requires = ["setuptools==80.9.0", "wheel==0.45.1"]
build-backend = "setuptools.build_meta"

[project]
name = "loggerizer"
version = "0.1.9"
description = "A flexible logging framework with JSON, file, and SMTP logging"
readme = "README.md"
requires-python = "~=3.11"
authors = [
    { name = "Ayman Kastali", email = "aymankastali.backend@gmail.com" }
]
license = "MIT"
dependencies = []

[project.urls]
Homepage = "https://github.com/AymanKastali/loggerizer"
Repository = "https://github.com/AymanKastali/loggerizer"

[tool.setuptools.packages.find]
where = ["."]
include = ["loggerizer*"]

[project.optional-dependencies]
dev = [
    "pytest==9.0.2",
    "pylint==4.0.4",
    "ruff==0.15.0",
    "twine==6.2.0",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
pythonVersion = "3.11"
typeCheckingMode = "basic"
extraPaths = [".venv/lib/python3.11/site-packages"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
